# Generated by Django 5.1 on 2024-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1000)),
                ('isbn', models.CharField(help_text='Please supply a 13 digit-long ISBN.', max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(default=0)),
                ('published_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
