# Generated by Django 5.1 on 2024-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
