version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_default_user
      - RABBITMQ_DEFAULT_PASS=rabbitmq_default_password
      - RABBITMQ_HOST='localhost'
      - RABBITMQ_PORT=5672
    ports:
      - "5672:5672"
      - "15672:15672"
