# Generated by Django 5.1 on 2024-09-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(help_text='Please supply a 13 digit-long ISBN.', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('recommended_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendationAPI.book')),
                ('recommended_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendationAPI.user')),
            ],
        ),
    ]
