# Generated by Django 5.1 on 2024-09-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommended_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='recommended_to_user',
            new_name='user',
        ),
    ]
