# Generated by Django 5.1 on 2024-09-02 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(help_text='Please supply a 13 digit-long ISBN.', max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Shipped'), ('D', 'Delivered'), ('C', 'Cancelled')], max_length=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BookLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('related_to_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderAPI.book')),
                ('placed_in_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderAPI.order')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='orders',
            field=models.ManyToManyField(through='orderAPI.BookLine', to='orderAPI.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='made_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderAPI.user'),
        ),
    ]
