# Generated by Django 5.1 on 2024-09-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookline',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='bookline',
            name='placed_in_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderAPI.order'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(help_text='Please supply a 13 digit-long ISBN.', max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(default=0)),
                ('orders', models.ManyToManyField(through='orderAPI.BookLine', to='orderAPI.order')),
            ],
        ),
        migrations.AddField(
            model_name='bookline',
            name='related_to_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderAPI.book'),
        ),
    ]
