# Generated by Django 5.1 on 2024-09-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0002_alter_book_isbn_alter_bookline_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookline',
            old_name='related_to_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookline',
            old_name='placed_in_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='made_by_user',
            new_name='user',
        ),
    ]
