# Generated by Django 5.1 on 2024-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAPI', '0003_rename_related_to_book_bookline_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='orderAPI.BookLine', to='orderAPI.book'),
        ),
    ]
