# Generated by Django 5.1 on 2024-09-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='book_reviewed',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='written_by_user',
            new_name='user',
        ),
    ]
